Business info page
sohumrao/JIC-4103-Beauty-Consulting-App pull request #27
Opened 2024-09-28 01:08 UTC by anand-ts

- Added business info page

2024-09-28 01:10 UTC, clarkcousins approved these changes
lgtm

2024-09-28 01:11 UTC, DavidHe137 requested changes
Adjust .gitignore please

2024-09-28 01:11 UTC, DavidHe137 commented on .gitignore
Should not ignore package.json, as this file is necessary for other collaborators to know which npm modules are needed.

2024-09-28 01:14 UTC, anand-ts commented on .gitignore
Changed!

2024-09-28 22:47 UTC, sohumraoGT approved these changes
LGTM

2024-09-29 06:09 UTC, achen443 approved these changes

2024-09-29 15:00 UTC, willshutt approved these changes
lgtm, great work on this

2024-09-29 15:05 UTC, merged

2024-09-29 21:14 UTC, anand-ts reviewed
LGTM!

2024-09-29 21:58 UTC, DavidHe137 reviewed
good