Appointments page updated v2
sohumrao/JIC-4103-Beauty-Consulting-App pull request #88
Opened 2024-11-07 04:03 UTC by anand-ts

- Updated Appointments Schema
- Updated Appointments Controller
- Updated Appointments Page

2024-11-07 17:37 UTC, DavidHe137 requested changes
Backend changes look pretty good, though there seems to be a bug with create appointment. Even though the API has not been fully connected with the backend, were you able to fully test the flow with with curl/Postman/Insomnia?

Also, please delete the commented code as we can use git history to keep track of past code versions.

2024-11-07 17:37 UTC, DavidHe137 commented on server/model/appointment.js
> +
Can this be deleted?

2024-11-07 17:37 UTC, DavidHe137 commented on server/route/AppointmentController.js
> +
Can this be deleted?

2024-11-07 17:37 UTC, DavidHe137 commented on server/route/AppointmentController.js
> +			.populate("stylist", "info.name");
When I test create appointment using Postman, I get the following error:
<img width="806" alt="Screen Shot 2024-11-07 at 12 34 27 PM" src="https://github.com/user-attachments/assets/511fc524-0a17-43f0-a81e-e6f40ed8818c">

2024-11-09 04:56 UTC, DavidHe137 requested changes
I am unable to run the backend with the original code. After fixing imports, signing in is broken as it seems this PR deletes the endpoint. Were you able to test on your machine?

2024-11-09 04:56 UTC, DavidHe137 commented on server/route/AccountController.js
> +	upload.single("photo"),
Why was this endpoint deleted?

2024-11-09 04:56 UTC, DavidHe137 commented on server/model/photo.js
> +export default Photo;
This is breaking imports. I am unable to start the backend with this change.

2024-11-09 05:39 UTC, anand-ts commented
Closing this PR since it got too convoluted because I combined Appointments Page and Photo Upload in one PR. Also this breaks Account Creation (my bad) so Appointments will have its own dedicated PR again.

2024-11-11 00:13 UTC, closed without merging